name: coffee_repository
description: "A test task for the Coffee company."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  sqflite: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0


flutter:
  generate: true
  uses-material-design: true